[phases.setup]
nixPkgs = ['...', 'nodejs_20']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction',
    'npm ci'
]

[phases.build]
cmds = [
    'npm run build',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan migrate --force && php -S 0.0.0.0:$PORT -t public'